### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by wayneconnolly** [FabioLuca/invst#5]
**Describe the bug**
Running analysis on GOOG via the flask web interface produces a Internal Server Error 500.

**To Reproduce**
1. Create and populate with a valid AV API Key cfg/api-cfg-access.json
2. Go to [invst flask homepage](http://172.17.0.2:8080) 
3. Input GOOG into the Analysis Symbol field
4. Click 'Run Analysis'

**Expected behavior**
Analysis runs

**ERROR**
```
 * Running on http://172.17.0.2:8080/ (Press CTRL+C to quit)

172.17.0.1 - - [18/Jan/2022 23:51:53] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [18/Jan/2022 23:51:53] "GET /static/styles/app.css HTTP/1.1" 304 -
172.17.0.1 - - [18/Jan/2022 23:51:58] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [18/Jan/2022 23:51:58] "GET /static/styles/app.css HTTP/1.1" 304 -
2022.01.18 11:52:11 PM - invst.run_analysis - INFO - 
2022.01.18 11:52:11 PM - invst.run_analysis - INFO - ========================== NEW RUN ==========================
2022.01.18 11:52:11 PM - invst.run_analysis.config - INFO - Initializing configuration.
2022.01.18 11:52:11 PM - invst.run_analysis.config - INFO - Loading the configuration from /invst/cfg/api-cfg.json.
2022.01.18 11:52:11 PM - invst.run_analysis.config - INFO - Successful loading the configuration from /invst/cfg/api-cfg.json.
2022.01.18 11:52:11 PM - invst.run_analysis.config - INFO - Loading the configuration from ../invst/cfg/api-cfg-access.json.
172.17.0.1 - - [18/Jan/2022 23:52:11] "POST /analysis HTTP/1.1" 500 -
```

**Comment by FabioLuca** [comment]
Just pushed an update for better handling error when loading files and also updated the documentation. Key point is that some time ago it was necessary to move the api-cfg-access.json to inside 'cfg/user' folder for compatibility with managing secrets in cloud operation. This was not documented yet.

File structure should be like this:
![image](https://user-images.githubusercontent.com/23051814/150203541-ccf67eb2-99bd-43ed-b9a4-2ad97f227414.png)

The file content is also important that the dict is complete, even if the value is blank. Below is a complete example, where the content is replaced by default values. Rename it to .json extension, replace with the proper key(s) and copy to the 'cfg/user' folder.
[api-cfg-access.txt](https://github.com/FabioLuca/invst/files/7900201/api-cfg-access.txt)

**Comment by wayneconnolly** [comment]
Thankyou
